### ISSUE TITLE
[configuration] Add `shared` as a value in addition to `private` and `public` in the *SUBUTAI_SCOPE* configuration parameter

### ISSUE THREAD

**Issue by jadilet** [subutai-io/vagrant#109]

**Comment by AlinaPenkina** [comment]
Fixed.

**Comment by Almansherov** [comment]
Before creation a VM I included *SUBUTAI_SCOPE* into file `vagrant-subutai.yml`.
VM was successfully created:

![image](https://user-images.githubusercontent.com/32430693/45356307-8b2d9480-b588-11e8-87c5-e79227486153.png)

**Comment by kurmanbekova6** [comment]
![screenshot from 2018-11-15 12-27-01](https://user-images.githubusercontent.com/9501291/48534395-2f59f180-e8d2-11e8-82c2-25726aaf7025.png)
Tested in prod
