### ISSUE TITLE
Enable SUBUTAI_DESKTOP provisioning option

### ISSUE THREAD

**Issue by jadilet** [subutai-io/vagrant#113]
Basically, if users set `SUBUTAI_DESKTOP` to true then the VM is set up like a client with everything.

**Comment by Almansherov** [comment]
Successfully created VM with the desktop inside:

![image](https://user-images.githubusercontent.com/32430693/45359065-06934400-b591-11e8-9a5f-03c8f8cd4acc.png)
fixed on master

**Comment by Almansherov** [comment]
Wrote a parameter in vagrant-subutai.yml file
Enabled subutai_desktop
and brought a peer up.
Result: Ended up with mate desktop 
Fixed
