### ISSUE TITLE
Error message during creating peer with Desktop

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/vagrant#116]
When user creates peer with SUBUTAI_DESKTOP in the end he gets this error message, actually peer created.
![image](https://user-images.githubusercontent.com/34295807/44204108-34908e80-a173-11e8-84a9-8bd1d8d333f3.png)

**Comment by Almansherov** [comment]
Fixed on master:

![image](https://user-images.githubusercontent.com/32430693/45359110-27f43000-b591-11e8-990f-ed2ad22aa0da.png)

Created a peer with `subutai_desktop` inside of `vagrant-subutai.yml` file.
using commands `vagrant init subutai/master-stretch` and `vagrant up`

**Comment by Almansherov** [comment]
Repeated these steps during testing p2p connectivity on desktop.
Fixed
