### ISSUE TITLE
Fix Vagrant so that it uses new CLI 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/vagrant#117]
We will be able to avoid this message during the installation: 

![image](https://user-images.githubusercontent.com/32430693/44767652-93490580-ab80-11e8-8fe3-02f48d74ac8e.png)

For more info:
https://optdyn.slack.com/archives/C93MLLTL4/p1535521197000100

**Comment by Almansherov** [comment]
Used the commands: `vagrant init subutai/stretch-master`
Vagrant used the new CLI and has got me a new versions of vagrant plugin and box:

![image](https://user-images.githubusercontent.com/32430693/45354534-726eb000-b583-11e8-847b-1380685a6d1d.png)

Issue is fixed on master

**Comment by kurmanbekova6** [comment]
Tested in prod
![screenshot from 2018-11-14 15-50-19](https://user-images.githubusercontent.com/9501291/48474604-15160a00-e825-11e8-8aa8-900eedcb1109.png)
