### ISSUE TITLE
Blueprint provisioning

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/vagrant#13]
Aim
----

Enable developers who use Subutai to launch entire application stacks using an application blueprint.

Usage
------

If a developer has a **Subutai.json** blueprint present in the same directory containing the Vagrantfile, the Subutai Vagrant Plugin should detect it, and automatically use it to build an environment (on the VM or multi-VM defined by the Vagrantfile) and deploy the blueprint into it.

As a developer this is very useful for me. I would like to erect a stack very quickly to test my code changes. A blueprint and a local environment is perfect. This makes Subutai and the Subutai Vagrant Plugin extremely useful for developers.

Implementation
--------------- 

Environments currently can be created in two modes: `peer` local mode, and `hub` mode. A `peer` environment can work without registering the peer with the Hub. It can also span multiple peers. If peers are subsequently registered on the Hub full management of these environments is not possible yet some functionality exists for that. 

If users want to create environments that are fully manageable by the Hub they need to create `hub` environments. This requires using the Hub API and any peers involved need to be registered on the Hub. Just the opposite of a `peer` environment, a `hub` environment cannot be fully managed on a peer's console. 

The plugin needs to be as intelligent as possible to prevent users from having to do too much work to get up and go with this blueprint provisioning feature. The plugin *MUST* use smart defaults to determine which mode of environment creation will be used. If Hub credentials are provided it should always default to `hub` environment creation mode, especially when the peer is configured to be registered with the Hub. If the peer is **NOT** setup to be registered, or Hub credentials are not available then it should default to building the environment in `peer` local environment creation mode.

In both cases the following steps are needed:

1. The plugin needs to launch the VM (or multi-machine environment - future capability) first
2. (future capability) If a multi-VM environment with RHs they need to be registered with the Peer

At this point we branch based on the availability of Hub credentials and based on the presence and value of an override variable **SUBUTAI_ENV_TYPE**. If **SUBUTAI_ENV_TYPE** is **NOT** set then we use the smart defaults described above. The **SUBUTAI_ENV_TYPE** variable overrides this smart default behavior. When set to `peer` it uses peer mode even if Hub credentials are available. If set to `hub` it uses hub API's to create the environment.

Using a Single Peer
-------------------

We could have just fed the Subutai.json to the Hub to automate this process. However I don't think there is an API for that #1, and #2 I don't think it will work without having a GitHub repository associated with the Hub account for the blueprint. So this might create problems.

Plus we do not want to create a multi-peer environment. We want all the containers to be on the local VM peer. I am thinking we parse the JSON to detect what needs to be done and do it. We can look at the hub code to get ideas on this.

So even if we use the Hub we will still be making all the containers reside locally on the newly built VM for now. We might get new ideas later. So this is why it might be best to just use both the Peer and Hub API to step by step create the environment instead of using the Hub's blueprint code.

**Comment by etursunbaev** [comment]
All issues in epic is closed. Closing
