### ISSUE TITLE
[Parallels] Cannot Create Virtual Disk  

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/vagrant#135]
While creating a peer on MacOS using parallels, there is an error with disk size. Parallels cannot create disk size.

Parameters of peer:

SUBUTAI_RAM : 4096
SUBUTAI_CPU : 1
SUBUTAI_ENV : master
DISK_SIZE : 200
BRIDGE : “en0”

pwd: /Users/admin/untitled folder/Subutai-peers/subutai-peer_fdvdffdvfd

Screenshot:
<img width="606" alt="screen shot 2018-11-05 at 5 00 23 pm" src="https://user-images.githubusercontent.com/32430693/47995682-b7aeea00-e0bb-11e8-9ed9-afa0bc6b5998.png">

How to reproduce:
* Bring a peer up on MacOS and monitor the process of creation

**Comment by Almansherov** [comment]
Successfully brought a peer up on macos:

<img width="605" alt="screen shot 2018-11-06 at 10 05 56 am" src="https://user-images.githubusercontent.com/32430693/48120973-4c8b2200-e239-11e8-8481-ae0aa8458422.png">

Fixed in master

**Comment by kurmanbekova6** [comment]
Tested in prod.
<img width="565" alt="screen shot 2018-11-14 at 5 31 08 pm" src="https://user-images.githubusercontent.com/9501291/48480021-4c8bb300-e833-11e8-9fa0-73e36b38106c.png">
