### ISSUE TITLE
Vagrant up gives error if pass disk as variable 

### ISSUE THREAD

**Issue by absidish** [subutai-io/vagrant#139]
```
SUBUTAI_DISK=300  vagrant up 
```

![screenshot from 2018-12-03 15-41-30](https://user-images.githubusercontent.com/8696139/49368655-755be580-f719-11e8-9321-f22cd0426cdd.png)

**Comment by Almansherov** [comment]
successfully brought a peer up:

![image](https://user-images.githubusercontent.com/32430693/50505897-afc85200-0a3b-11e9-972c-deb458718f85.png)

Fixed in master

**Comment by Almansherov** [comment]
Fixed in prod
