### ISSUE TITLE
Register peer to HUB

### ISSUE THREAD

**Issue by jadilet** [subutai-io/vagrant#2]
Need REST API from hub.
We can register peer via plugin like this command:
`vagrant subutai -r`

**Comment by akarasulu** [comment]
Check with @samsonbek who implemented this to be able to have cloud peers register with the Hub. The code to do this is already out there. Find it and convert it into Ruby. Add this to the subutai_net module as a function for now. Then you can look into incorporating it into the Vagrant plugin.
