### ISSUE TITLE
Validate the Blueprint file (Subutai.json) before building the environment

### ISSUE THREAD

**Issue by jadilet** [subutai-io/vagrant#35]

**Comment by akarasulu** [comment]
What does this mean and entail? This is an open source project, you have to make an effort to put more detail here. This is open information, everyone sees it. If I'm an employer and I Google for Adilet what will I think ;).

**Comment by jadilet** [comment]
Its validate Subutai Blueprint Subutai.json file. The user might be missed some required JSON keys or values in Subutai.json. It says where was going wrong in Subutai.json.
