### ISSUE TITLE
Add error handler for user configuration

### ISSUE THREAD

**Issue by jadilet** [subutai-io/vagrant#90]

**Comment by jadilet** [comment]
Plugin validates user configuration parameter types. It fails if you set incorrect type. User Configuration parameter docs [here](https://github.com/subutai-io/vagrant/wiki/Configuration-Parameters)

**Comment by ibragim13kz** [comment]
@jadilet You mean it fails if I will put, for example, wrong parameter to `.yml file`?

**Comment by ibragim13kz** [comment]
Done in Prod.
