### ISSUE TITLE
BRIDGE Configuration Property Enhancements

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/vagrant#94]
**NOTE**: This is not a critical bug since work arounds exist for the user and the feature is a convenience to begin with. It is also rare for users to be using multiple providers at the same time like our testers do.

Problem
--------

The BRIDGE configuration property is used to select the bridge name used by the vagrant plugin and is applied across all hypervisors.  Unfortunately vagrant providers for different hypervisors do not consistently use the same name/identifier for the bridge interface.

For example, using virtualbox on Mac OS the bridge was `en0: Ethernet 1`, yet on the same physical machine when using the parallels hypervisor and vagrant provider the bridge was `en0`. As a result, when a user sets `BRIDGE='en0: Ethernet 1` in their user configurations, vagrant does not prompt the user to select the bridge interface when using virtualbox. When using parallels on the same machine the user is still prompted because according to vagrant's parallels provider `en0: Ethernet 1` does not exist: `en0` does however.  If the user sets `BRIDGE='en0'` then the opposite problem occurs.

Solution
--------

The "general" `BRIDGE` configuration property should be overridden or set to the hypervisor/provider specific bridge configuration properties like:

* BRIDGE_VIRTUALBOX
* BRIDGE_PARALLELS
* BRIDGE_VMWARE
* BRIDGE_KVM
* BRIDGE_HYPERV

The hypervisor/provider specific bridge configuration property is considered **activated** when the current hypervisor/provider being used matches the property's hypervisor suffix. When **active** with non-nil value, it should override the BRIDGE property.

Users may decide not to set the BRIDGE property at all to instead set each individual hypervisor specific property. In this case, the plugin must consider setting the nil BRIDGE property to whatever value is held by the **activated** more specific hypervisor/provider bridge configuration parameter.

**Comment by ibragim13kz** [comment]
Done in Prod.
